### ISSUE TITLE
Failed to generate charts for AV dataset  - iPres2022 Bake Off 

### ISSUE THREAD

**Issue by joshuatj** [ablwr/media-collection-viewer#5]
Hi Ashley,

Not sure what happened, but "Build charts" return empty charts for the iPres2022 Bake Off AV dataset. I've included the errors from Console below. I've also extracted just the AV data set and shared it via my own Google Drive. Inside the Google Drive are the MediaInfo generate JSONs. 

Happy to supply more logs or information to diagnose this error. 

Challenge: https://ipres2022.scot/call-for-contributions-2/digital-preservation-bake-off-challenge/ 
[AV Data Set + generated JSON](https://drive.google.com/drive/folders/1k9hKp5YhS3-RRje4qlvrzF51--3x3bKY?usp=sharing) 
Full Data Set: https://ipres2022.scot/call-for-contributions-2/data-set/

### 1st error:
wasm-loader.js:293
panicked at 'called `Option::unwrap()` on a `None` value', src/components/charts.rs:227:52

Stack:

parcelRequire<.fISM</_.__wbg_new_59cb74e423758ede@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:3851
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[322]:0x48638
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[811]:0x59aab
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[462]:0x52b57
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[522]:0x5558e
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[679]:0x58d8f
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[659]:0x5899f
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[680]:0x58dc5
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[641]:0x584f9
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[87]:0x90cc
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[156]:0x2cdb8
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[197]:0x369ba
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[195]:0x36314
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[421]:0x50536
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[173]:0x31359
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[655]:0x58865
O@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:2624
c@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:2229
EventListener.handleEvent*parcelRequire<.fISM</_.__wbg_addEventListener_c11a938b8469ab06<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:6290
parcelRequire<.fISM</k/<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:2828
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[628]:0x58127
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[371]:0x4cbb0
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[203]:0x37c52
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[127]:0x23924
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[119]:0x20958
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[197]:0x369ba
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[195]:0x36314
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[255]:0x40761
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[443]:0x519de
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[653]:0x587fa
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[655]:0x58865
O@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:2624
c@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:2229
EventListener.handleEvent*parcelRequire<.fISM</_.__wbg_addEventListener_c11a938b8469ab06<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:6290
parcelRequire<.fISM</k/<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:2828
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[628]:0x58127
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[324]:0x489e5
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[91]:0x11b2c
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[191]:0x3551a
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[159]:0x2dbdb
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[90]:0x1087f
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[91]:0x12002
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[191]:0x3551a
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[159]:0x2dbdb
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[90]:0x1087f
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[91]:0x12002
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[191]:0x3551a
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[136]:0x27034
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[197]:0x369ba
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[227]:0x3c231
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[307]:0x46d6a
@https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm:wasm-function[687]:0x58eff
parcelRequire<.fISM</_.run@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:22:3479
parcelRequire<.QCba<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:12:211
f@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:1:468
p@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:1:544
parcelRequire<[0]</<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:24:143
promise callback*parcelRequire<[0]<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:24:120
f@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:1:468
parcelRequire<@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:1:772
@https://bits.ashleyblewer.com/media-collection-viewer/static.91ea28f3.js:1:1023

wasm-loader.js:293
    __wbg_error_4bb6c2a97407129a wasm-loader.js:293
    <anonymous> media_collection_viewer_bg.1e878511.wasm:296685
    <anonymous> media_collection_viewer_bg.1e878511.wasm:367275
    <anonymous> media_collection_viewer_bg.1e878511.wasm:338775
    <anonymous> media_collection_viewer_bg.1e878511.wasm:349582
    <anonymous> media_collection_viewer_bg.1e878511.wasm:363919
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362911
    <anonymous> media_collection_viewer_bg.1e878511.wasm:363973
    <anonymous> media_collection_viewer_bg.1e878511.wasm:361721
    <anonymous> media_collection_viewer_bg.1e878511.wasm:37068
    <anonymous> media_collection_viewer_bg.1e878511.wasm:183736
    <anonymous> media_collection_viewer_bg.1e878511.wasm:223674
    <anonymous> media_collection_viewer_bg.1e878511.wasm:221972
    <anonymous> media_collection_viewer_bg.1e878511.wasm:329014
    <anonymous> media_collection_viewer_bg.1e878511.wasm:201561
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362597
    O wasm-loader.js:226
    c wasm-loader.js:194
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_c11a938b8469ab06 wasm-loader.js:419
    k wasm-loader.js:241
    <anonymous> media_collection_viewer_bg.1e878511.wasm:360743
    <anonymous> media_collection_viewer_bg.1e878511.wasm:314288
    <anonymous> media_collection_viewer_bg.1e878511.wasm:228434
    <anonymous> media_collection_viewer_bg.1e878511.wasm:145700
    <anonymous> media_collection_viewer_bg.1e878511.wasm:133464
    <anonymous> media_collection_viewer_bg.1e878511.wasm:223674
    <anonymous> media_collection_viewer_bg.1e878511.wasm:221972
    <anonymous> media_collection_viewer_bg.1e878511.wasm:264033
    <anonymous> media_collection_viewer_bg.1e878511.wasm:334302
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362490
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362597
    O wasm-loader.js:226
    c wasm-loader.js:194
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_c11a938b8469ab06 wasm-loader.js:419
    k wasm-loader.js:241
    <anonymous> media_collection_viewer_bg.1e878511.wasm:360743
    <anonymous> media_collection_viewer_bg.1e878511.wasm:297445
    <anonymous> media_collection_viewer_bg.1e878511.wasm:72492
    <anonymous> media_collection_viewer_bg.1e878511.wasm:218394
    <anonymous> media_collection_viewer_bg.1e878511.wasm:187355
    <anonymous> media_collection_viewer_bg.1e878511.wasm:67711
    <anonymous> media_collection_viewer_bg.1e878511.wasm:73730
    <anonymous> media_collection_viewer_bg.1e878511.wasm:218394
    <anonymous> media_collection_viewer_bg.1e878511.wasm:187355
    <anonymous> media_collection_viewer_bg.1e878511.wasm:67711
    <anonymous> media_collection_viewer_bg.1e878511.wasm:73730
    <anonymous> media_collection_viewer_bg.1e878511.wasm:218394
    <anonymous> media_collection_viewer_bg.1e878511.wasm:159796
    <anonymous> media_collection_viewer_bg.1e878511.wasm:223674
    <anonymous> media_collection_viewer_bg.1e878511.wasm:246321
    <anonymous> media_collection_viewer_bg.1e878511.wasm:290154
    <anonymous> media_collection_viewer_bg.1e878511.wasm:364287
    run wasm-loader.js:235
    QCba index.ts:5
    f static.91ea28f3.js:1
    p static.91ea28f3.js:1
    parcelRequire<[0]</< static.91ea28f3.js:24
    (Async: promise callback)
    parcelRequire<[0]< static.91ea28f3.js:24
    f static.91ea28f3.js:1
    parcelRequire static.91ea28f3.js:1
    <anonymous> static.91ea28f3.js:1

### Second error:
[media_collection_viewer_bg.1e878511.wasm:338829:1](https://bits.ashleyblewer.com/media-collection-viewer/media_collection_viewer_bg.1e878511.wasm)
Uncaught RuntimeError: unreachable executed
    O wasm-loader.js:226
    c wasm-loader.js:194
    __wbg_addEventListener_c11a938b8469ab06 wasm-loader.js:419
    k wasm-loader.js:241
    O wasm-loader.js:226
    c wasm-loader.js:194
    __wbg_addEventListener_c11a938b8469ab06 wasm-loader.js:419
    k wasm-loader.js:241
    run wasm-loader.js:235
    QCba index.ts:5
    f static.91ea28f3.js:1
    p static.91ea28f3.js:1
    parcelRequire<[0]</< static.91ea28f3.js:24
    promise callback*parcelRequire<[0]< static.91ea28f3.js:24
    f static.91ea28f3.js:1
    parcelRequire static.91ea28f3.js:1
    <anonymous> static.91ea28f3.js:1
media_collection_viewer_bg.1e878511.wasm:338829:1
    <anonymous> media_collection_viewer_bg.1e878511.wasm:338829
    <anonymous> media_collection_viewer_bg.1e878511.wasm:349582
    <anonymous> media_collection_viewer_bg.1e878511.wasm:363919
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362911
    <anonymous> media_collection_viewer_bg.1e878511.wasm:363973
    <anonymous> media_collection_viewer_bg.1e878511.wasm:361721
    <anonymous> media_collection_viewer_bg.1e878511.wasm:37068
    <anonymous> media_collection_viewer_bg.1e878511.wasm:183736
    <anonymous> media_collection_viewer_bg.1e878511.wasm:223674
    <anonymous> media_collection_viewer_bg.1e878511.wasm:221972
    <anonymous> media_collection_viewer_bg.1e878511.wasm:329014
    <anonymous> media_collection_viewer_bg.1e878511.wasm:201561
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362597
    O wasm-loader.js:226
    c wasm-loader.js:194
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_c11a938b8469ab06 wasm-loader.js:419
    k wasm-loader.js:241
    <anonymous> media_collection_viewer_bg.1e878511.wasm:360743
    <anonymous> media_collection_viewer_bg.1e878511.wasm:314288
    <anonymous> media_collection_viewer_bg.1e878511.wasm:228434
    <anonymous> media_collection_viewer_bg.1e878511.wasm:145700
    <anonymous> media_collection_viewer_bg.1e878511.wasm:133464
    <anonymous> media_collection_viewer_bg.1e878511.wasm:223674
    <anonymous> media_collection_viewer_bg.1e878511.wasm:221972
    <anonymous> media_collection_viewer_bg.1e878511.wasm:264033
    <anonymous> media_collection_viewer_bg.1e878511.wasm:334302
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362490
    <anonymous> media_collection_viewer_bg.1e878511.wasm:362597
    O wasm-loader.js:226
    c wasm-loader.js:194
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_c11a938b8469ab06 wasm-loader.js:419
    k wasm-loader.js:241
    <anonymous> media_collection_viewer_bg.1e878511.wasm:360743
    <anonymous> media_collection_viewer_bg.1e878511.wasm:297445
    <anonymous> media_collection_viewer_bg.1e878511.wasm:72492
    <anonymous> media_collection_viewer_bg.1e878511.wasm:218394
    <anonymous> media_collection_viewer_bg.1e878511.wasm:187355
    <anonymous> media_collection_viewer_bg.1e878511.wasm:67711
    <anonymous> media_collection_viewer_bg.1e878511.wasm:73730
    <anonymous> media_collection_viewer_bg.1e878511.wasm:218394
    <anonymous> media_collection_viewer_bg.1e878511.wasm:187355
    <anonymous> media_collection_viewer_bg.1e878511.wasm:67711
    <anonymous> media_collection_viewer_bg.1e878511.wasm:73730
    <anonymous> media_collection_viewer_bg.1e878511.wasm:218394
    <anonymous> media_collection_viewer_bg.1e878511.wasm:159796
    <anonymous> media_collection_viewer_bg.1e878511.wasm:223674
    <anonymous> media_collection_viewer_bg.1e878511.wasm:246321
    <anonymous> media_collection_viewer_bg.1e878511.wasm:290154
    <anonymous> media_collection_viewer_bg.1e878511.wasm:364287
    run wasm-loader.js:235
    QCba index.ts:5
    f static.91ea28f3.js:1
    p static.91ea28f3.js:1
    parcelRequire<[0]</< static.91ea28f3.js:24
    (Async: promise callback)
    parcelRequire<[0]< static.91ea28f3.js:24
    f static.91ea28f3.js:1
    parcelRequire static.91ea28f3.js:1
    <anonymous> static.91ea28f3.js:1

**Comment by ablwr** [comment]
Awesome, thank you!!! I'll look at the dataset and see what caused the panic.

**Comment by ablwr** [comment]
From a quick glance, looks like it could be as small as a blank field that was expected/"required".

It looks like it could be this one: `D:\\dev\\iPRES2022\\Bake Off\\iPres2022_Data-Set\\AV\\ipres2015_dataset\\flash1 - ILLCS6.swf"` (and another Flash file)

...Because it's marked as a Video but does not have a `Format`, which I expected to always be present for Video streams.

Will fix!

**Comment by ablwr** [comment]
The merging of this PR auto-closed this Issue. I tested with the `0_AV_all.json` file, assuming that has all of them, which was failing in production and now works on local dev (& should auto-deploy to production now).

**Comment by ablwr** [comment]
Now it's deployed -- forgot this was a manual step. :blush:

**Comment by joshuatj** [comment]
I can confirm that the bug is fixed and the tool is baking pies again (Micky said it's very thematic that I was showing pies at a digipres bake off 🤣)
